import { cx, focusRing } from "./ui";

// Generated by tools/generate-website-brand.py from apps/desktop/assets/logo.png.
const srcSet = (variant: "light" | "dark") =>
  `/brand/logo-${variant}-96.webp 1x, /brand/logo-${variant}-192.webp 2x, /brand/logo-${variant}-288.webp 3x`;

/**
 * The ASDesk lockup. The light-theme file has the original grey wordmark; the dark-theme file
 * repaints it near-white. Both are rendered and the theme class picks one, so switching themes
 * never flashes an empty slot.
 */
export function Logo({ size = "md", eager = false }: { size?: "sm" | "md"; eager?: boolean }) {
  const image = cx("w-auto", size === "md" ? "h-10 sm:h-11" : "h-9");
  const loading = eager ? "eager" : "lazy";
  return (
    <a href="#top" className={cx("inline-flex shrink-0 rounded-lg", focusRing)}>
      <img
        src="/brand/logo-light-96.webp"
        srcSet={srcSet("light")}
        width={96}
        height={47}
        alt="ASDesk"
        loading={loading}
        decoding="async"
        className={cx(image, "dark:hidden")}
      />
      <img
        src="/brand/logo-dark-96.webp"
        srcSet={srcSet("dark")}
        width={96}
        height={47}
        alt="ASDesk"
        loading={loading}
        decoding="async"
        className={cx(image, "hidden dark:block")}
      />
    </a>
  );
}

/** The AS + monitor mark on its own, for small placements such as the product mock-up. */
export function Mark({ className }: { className?: string }) {
  return (
    <img
      src="/brand/mark-32.webp"
      srcSet="/brand/mark-32.webp 1x, /brand/mark-64.webp 2x, /brand/mark-96.webp 3x"
      width={32}
      height={21}
      alt=""
      decoding="async"
      className={cx("w-auto", className)}
    />
  );
}
