"""Export scraped products to JSON, CSV, Excel and/or a clean HTML catalog."""

from __future__ import annotations

import json
import os
import html
import datetime
from urllib.parse import urlparse

from .models import Product


def export(products: list[Product], out_dir: str, basename: str, formats: list[str]) -> list[str]:
    """Write the requested formats. Returns the list of files written."""
    os.makedirs(out_dir, exist_ok=True)
    written = []
    formats = [f.lower().lstrip(".") for f in formats]

    if "json" in formats:
        path = os.path.join(out_dir, f"{basename}.json")
        with open(path, "w", encoding="utf-8") as fh:
            json.dump([p.to_dict() for p in products], fh, indent=2, ensure_ascii=False)
        written.append(path)

    if {"csv", "xlsx", "excel"} & set(formats):
        rows = [p.to_flat_dict() for p in products]
        import pandas as pd

        df = pd.DataFrame(rows)
        if "csv" in formats:
            path = os.path.join(out_dir, f"{basename}.csv")
            df.to_csv(path, index=False, encoding="utf-8-sig")  # BOM = Excel-friendly
            written.append(path)
        if {"xlsx", "excel"} & set(formats):
            path = os.path.join(out_dir, f"{basename}.xlsx")
            df.to_excel(path, index=False)
            written.append(path)

    if "html" in formats:
        path = os.path.join(out_dir, f"{basename}.html")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(_render_html(products))
        written.append(path)

    return written


# --------------------------------------------------------------------------
# Clean HTML catalog
# --------------------------------------------------------------------------
_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{shop} — Product Catalog ({count})</title>
<style>
  :root {{ color-scheme: light dark; }}
  * {{ box-sizing: border-box; }}
  body {{ font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
         margin: 0; background: #f4f5f7; color: #1c1e21; }}
  header {{ position: sticky; top: 0; background: #1f2937; color: #fff;
           padding: 18px 24px; box-shadow: 0 2px 8px rgba(0,0,0,.15); z-index: 10; }}
  header h1 {{ margin: 0; font-size: 20px; font-weight: 600; }}
  header p {{ margin: 4px 0 0; opacity: .75; font-size: 13px; }}
  .toolbar {{ padding: 14px 24px; }}
  .toolbar input {{ width: 100%; max-width: 420px; padding: 10px 14px; font-size: 14px;
                   border: 1px solid #cbd2d9; border-radius: 8px; }}
  .grid {{ display: grid; gap: 18px; padding: 8px 24px 40px;
          grid-template-columns: repeat(auto-fill, minmax(230px, 1fr)); }}
  .card {{ background: #fff; border: 1px solid #e5e7eb; border-radius: 12px;
          overflow: hidden; display: flex; flex-direction: column;
          transition: box-shadow .15s, transform .15s; }}
  .card:hover {{ box-shadow: 0 8px 24px rgba(0,0,0,.12); transform: translateY(-2px); }}
  .thumb {{ aspect-ratio: 1/1; background: #fafafa; display: flex;
           align-items: center; justify-content: center; overflow: hidden; }}
  .thumb img {{ width: 100%; height: 100%; object-fit: contain; }}
  .no-img {{ color: #9aa5b1; font-size: 13px; }}
  .body {{ padding: 12px 14px 16px; display: flex; flex-direction: column; gap: 6px;
          flex: 1; }}
  .brand {{ font-size: 11px; letter-spacing: .04em; text-transform: uppercase;
           color: #7b8794; }}
  .name {{ font-size: 14px; font-weight: 600; line-height: 1.35;
          display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;
          overflow: hidden; }}
  .name a {{ color: inherit; text-decoration: none; }}
  .name a:hover {{ text-decoration: underline; }}
  .meta {{ margin-top: auto; display: flex; align-items: baseline;
          justify-content: space-between; gap: 8px; }}
  .price {{ font-size: 17px; font-weight: 700; color: #b91c1c; }}
  .stock {{ font-size: 11px; padding: 2px 8px; border-radius: 999px;
           background: #ecfdf5; color: #047857; white-space: nowrap; }}
  .stock.out {{ background: #fef2f2; color: #b91c1c; }}
  footer {{ text-align: center; color: #9aa5b1; font-size: 12px; padding: 24px; }}
</style>
</head>
<body>
<header>
  <h1>{shop} — Product Catalog</h1>
  <p>{count} products · scraped from <a href="{shop_url}" style="color:#93c5fd">{shop}</a> · exported {exported}</p>
</header>
<div class="toolbar">
  <input id="q" type="search" placeholder="Filter products…"
         oninput="filter(this.value)">
</div>
<div class="grid" id="grid">
{cards}
</div>
<footer>Generated by E-commerce Scraper</footer>
<script>
function filter(q) {{
  q = q.toLowerCase();
  document.querySelectorAll('.card').forEach(c => {{
    c.style.display = c.dataset.search.includes(q) ? '' : 'none';
  }});
}}
</script>
</body>
</html>
"""


def _render_html(products: list[Product]) -> str:
    cards = "\n".join(_render_card(p) for p in products)
    shop, shop_url = _shop_identity(products)
    exported = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return _HTML_TEMPLATE.format(
        count=len(products), cards=cards,
        shop=html.escape(shop), shop_url=html.escape(shop_url, quote=True),
        exported=html.escape(exported),
    )


def _shop_identity(products: list[Product]) -> tuple[str, str]:
    """Derive a shop name and homepage URL from the scraped product URLs."""
    for p in products:
        if p.url:
            parsed = urlparse(p.url)
            host = parsed.netloc.replace("www.", "")
            if host:
                return host, f"{parsed.scheme}://{parsed.netloc}/"
    return "Unknown source", "#"


def _render_card(p: Product) -> str:
    # Prefer a downloaded local file; otherwise use the remote image URL.
    img_src = p.image_files[0] if p.image_files else (p.images[0] if p.images else "")
    if img_src:
        thumb = f'<img src="{html.escape(img_src, quote=True)}" loading="lazy" alt="">'
    else:
        thumb = '<span class="no-img">no image</span>'

    name = html.escape(p.name or "Untitled")
    name_html = f'<a href="{html.escape(p.url, quote=True)}" target="_blank">{name}</a>' if p.url else name

    if p.price is not None:
        price = f"{p.price:,.2f}"
        if p.currency:
            price = f"{html.escape(p.currency)} {price}"
        price_html = f'<span class="price">{price}</span>'
    else:
        price_html = '<span class="price" style="color:#9aa5b1">—</span>'

    stock_html = ""
    if p.availability:
        out = "instock" not in p.availability.lower().replace(" ", "")
        stock_html = f'<span class="stock {"out" if out else ""}">{html.escape(p.availability)}</span>'

    brand_html = f'<div class="brand">{html.escape(p.brand)}</div>' if p.brand else ""
    search_blob = html.escape(" ".join(filter(None, [p.name, p.brand, p.sku])).lower(), quote=True)

    return f"""  <div class="card" data-search="{search_blob}">
    <div class="thumb">{thumb}</div>
    <div class="body">
      {brand_html}
      <div class="name">{name_html}</div>
      <div class="meta">{price_html}{stock_html}</div>
    </div>
  </div>"""
